server {
    listen 80;
    server_name bit-lab.tech www.bit-lab.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bit-lab.tech www.bit-lab.tech;

    ssl_certificate /etc/ssl/cloudflare/bit-lab.tech.pem;
    ssl_certificate_key /etc/ssl/cloudflare/bit-lab.tech.key;

    root /var/www/bit-lab.tech;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /opencdj {
        alias /var/www/opencdj;
        try_files $uri $uri/ /opencdj/index.html;
    }
}
